### ISSUE TITLE
planning v0.5.0 release

### ISSUE THREAD

**Issue by grlee77** [PyWavelets/pywt#203]
I think we have reached a sufficient number of new features that it would be nice to do another release soon. Does @PyWavelets/core agree? Any suggested date to target?

Are there other things people would like to see prior to release?  If so please add to the checklist below

**Since 0.4.0 we have merged:**
- 1D continuous wavelet transforms
- new discrete wavelets added (additional Debauchies and Coiflet wavelets)
- new 'reflect' extension mode for discrete wavelet transforms
- routines to convert multilevel DWT coefficients to and from single array
- substantial refactoring/reorganization of the underlying C and Cython code

**and could probably finish the existing PRs for:**
- faster performance for multilevel stationary wavelet transforms
- axis support for multilevel DWT
- (maybe?) benchmarking via ASV

TODO
- [x] add documentation for CWT
- [x] document new DWT coefficient reshaping routines (PR at #208)
- [x] update index.rst of the docs to reflect new features  (PR at #207)
- [x] update release notes (PR at #206)
- [x] handful of existing PRs to review/merge #179,  (#158?)
- [x] iswt and iswt2 from the last release should also be added to the API documentation
- [x] fix or remove broken doctests (see issue #209)

**Comment by grlee77** [comment]
@holgern
Are you interested in adding some brief API documentation for the CWT routines you recently contributed?  This would involve the following steps:

- add an entry for cwt to doc/source/ref/index.rst
- add a new cwt.rst file in doc/source/ref following the examples for the existing files in that folder.

**Comment by rgommers** [comment]
Agreed, +1 for new release. 

I have some time next week for reviewing open PRs. And I can do some of the doc writing that's still needed. Will start with ``iswt``/``iswt2`` unless someone has something already in the work.

**Comment by holgern** [comment]
I can do the cwt documentation. 

I am planing also to add denoising algorithm for dwt. (similar to matlab function wden).

**Comment by grlee77** [comment]
Thanks @holgern

As far as `wden`, there may be a comparable routine, but with n-dimensional support in scikit-image (on master, not yet released).  Specifically, there is `denoise_wavelet` which is an n-dimensional denoising routine based on thresholding coefficients and a routine `estimate_sigma` that estimates Gaussian noise standard deviation.  PyWavelets will be a dependency of `scikit-image` as of the next release.

See here:
https://github.com/scikit-image/scikit-image/blob/682d7e68aeaf20cddfb4d6f71ded2f4e88f8a557/skimage/restoration/_denoise.py#L482

**Comment by grlee77** [comment]
@rgommers.  I went ahead and added `iswt` and `iswt2` docs while I was adding `swtn` in #229

**Comment by rgommers** [comment]
>  went ahead and added ``iswt`` and ``iswt2`` docs while I was adding ``swtn``

thanks! you're way too fast for me, can barely keep up with reviewing:)

getting close to checking all the boxes here, a couple more open PRs....

**Comment by rgommers** [comment]
I think we're all good to go for a last update of the release notes and setting the version number to ``v0.5.0``. Any objections, or shall we call it good?

**Comment by grlee77** [comment]
sounds good.  I should be able to do a release tomorrow.  If you want to go ahead and do it sooner, that is fine too.

**Comment by rgommers** [comment]
release notes are up to date, changing version number in gh-239. Then it's just a matter of uploading some stuff according to http://pywavelets.readthedocs.io/en/latest/dev/how_to_release.html. I see that doc is still missing info on OS X binaries and the conda-forge package. I'll look at adding that tomorrow.

**Comment by grlee77** [comment]
I will do the uploads.  I am already a maintainer on the conda-forge package, so I can do the update there as well.

**Comment by grlee77** [comment]
@rgommers 
I think I completed everything for the release except:
- what is the process for OS X binaries?
- updating the outdated documentation at PyPI as discussed in #215

**Comment by rgommers** [comment]
Thanks @grlee77. I'll update the dev docs with those things now.
